### ISSUE TITLE
Idea: better templating system

### ISSUE THREAD

**Issue by Kamilcuk** [tylov/STC#10]
Writing [long macros](https://github.com/tylov/STC/blob/master/include/stc/clist.h#L105) certainly is not ideal and is hard to format and can result in bugs and pain when developing. Consider using a more powerful preprocessor to generate C source code, like jinja2 (my recommendation), php or m4. For example, the following code:

```
// clang-format off
{% macro define_macro(name, params) %}
#define {{ name }}{{ params }}
	{{- caller() | replace("CX_", "CX##_") | replace("\n", " \\\n") }}
{% endmacro %}
// clang-format on

// clang-format off
{% call define_macro("_c_using_clist", "(CX, Value, valueCompareRaw)") %}
// clang-format on

typedef RawValue CX_rawvalue_t;

STC_API CX CX_clone(CX cx);
STC_API void CX_del(CX *self);
STC_API void CX_push_back(CX *self, Value value);

// clang-format off
{% endcall %}
// clang-format on
```

It can be formatted with `clang-format` for nice looking code and there is no need to remember to type `\` every line. Then the code can be run via pythons jinja2 to output:

```
// clang-format off

// clang-format on

// clang-format off

#define _c_using_clist(CX, Value, valueCompareRaw) \
// clang-format on \
 \
typedef RawValue CX##_rawvalue_t; \
 \
STC_API CX CX##_clone(CX cx); \
STC_API void CX##_del(CX *self); \
STC_API void CX##_push_back(CX *self, Value value); \
 \
// clang-format off \


// clang-format on
```

This is just an implementation idea. Consider closing the issue after reading it.

**Comment by tylov** [comment]
I have though about this and certainly agree that the long macros are a problem. I also know about jinja2 from flask development, but I prefer to avoid third party tools for this lib.  

However, I have started to transform the code to use templates differently. It uses the ideas from https://github.com/glouw/ctl. It is much better to develop code this way, and even simpler for users IMO, as the template args are easier to specify. For simple cases, e.g. an int vector, only two lines as before is required to specify it:

#define i_VAL int
#include <stc/cvec.h>

Checkout the newstyle branch. Only cvec.h and clist.h are currently ready. It is now easy to forward declare all containers. See the temporay examples in include/stc folder.
