### ISSUE TITLE
cstr_assign_n behavior change

### ISSUE THREAD

**Issue by murtazahakim** [tylov/STC#24]
I am observing that the following code is crashing with the latest code.  
```
cstr a = cstr_init();
cstr_assign_n(&a, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", 32)
```
I am wondering if the behavior of `cstr_assign_n` has changed, in that I have to resize `cstr a` before assigning to it? 

Sincerely,

**Comment by tylov** [comment]
Thanks for reporting! Fix has been pushed.
