### ISSUE TITLE
c_umul128 undefined

### ISSUE THREAD

**Issue by dananderson** [tylov/STC#30]
STC
version 3.5.1

GCC
4.9.4, arm (https://github.com/rvagg/rpi-newer-crosstools/tree/master/x64-gcc-4.9.4-binutils-2.28/arm-rpi-linux-gnueabihf)

Code

#define i_key_str
#include "stc/cvec.h"

Expected

Successful compile!

Actual

GCC complains about c_umul128() function being undefined.

fastrange_size_t() calls this macro, but the macro does not get generated. The compiler does not have __SIZEOF_INT128__ defined, so I assume it does not support for 128 bit integers. My i_size is uint32_t, so I never call fastrange_size_t() at runtime. I am able to work around the issue by adding a linker flag: -Wl,-u,c_umul128. The issue does not appear on MSVC, apple clang, x64 gcc 8, aarch64 gcc 8, etc.

**Comment by dananderson** [comment]
Thanks for the quick response.

Also, veil and lse use gitmodules to import STC. It's convenient to set the branch to a tagged release, but the last tag is 3.5.1 and it looks like the apis have matured since then.

**Comment by tylov** [comment]
Yes, I have been sloppy on this, I'll try to make proper tagged versions going forward.
