### ISSUE TITLE
Proposal: change `*drop` to another name

### ISSUE THREAD

**Issue by data-man** [tylov/STC#33]
More commonly used names in other programming languages and libraries are "free" or "destroy".

**Comment by tylov** [comment]
I don't care much for the traditional create/destroy idiom. In general the element to be "created" already exist, but needs to be initialized. The opposite operation doesn't normally even modify (destroy) the element - it just frees potential resources it owns and should not be used anymore (it is still around - not "destroyed"). In that sense, "free" is better, but it could cause confusion: 
` Vec* vec = malloc(sizeof Vec); *vec = cvec_init(); Vec_push(vec, 1); ... Vec_free(vec); free(vec);`
Some could believe Vec_free(p) actually also calls free(p) and/or require a heap allocated object.
I will stick with the Rust idiom, drop. It is both short and easy to write/read and the name describes the operation well.

**Comment by data-man** [comment]
It's strange that you use words from Rust in the C library.
Why not new/delete from C++ stdlib?

**Comment by data-man** [comment]
I'll try to explain in more detail why I don't like "drop".
In your library I see the potential to develop different iterators like [C++20 ranges](https://en.cppreference.com/w/cpp/ranges).
C++20 ranges implements `drop_while` and `drop_while_view`.
Another widely used Rust library, [itertools](https://github.com/rust-itertools/itertools), also has a lot `drop*` iterators.

**Comment by tylov** [comment]
Well, the majority of functions and type names in STC are from C++ STL. Still, C is more similar to how Rust works than C++: Rust has default move semantics like C, no overloading, no inheritance, no constructors or special operators like C++ has.

I see your point with c++ ranges, but it doesn't need to use the exact same names, in fact ranges in C will be quite different.
Btw, in the dev branch, all iterators are now self-contained, i.e. only *begin() and *next() are needed, and .ref always becomes NULL at container end. No changes to the API, though.

But I have looked at alternatives to "drop" before. One I will consider for STC V4 is "dump". It is more precise, but is short and nice like drop. Naming is the most difficult part of programming.

**Comment by liigo** [comment]
"free" or "destroy" have their own pair: alloc/free, create/destroy (and new/delete). so i don't think any of them is the friend of "init".

i do think "drop" is a good name: init/drop, or new/drop. (and maybe "fini" is another good one: init/fini feels well.)

**Comment by tylov** [comment]
I will keep drop, as I like it better than destroy and other alternatives, and it is used in Rust as destructor name. There is a c_FLT_SKIPWHILE macro which works similar to Rust "skip_while" and c++ "drop_while".
