### ISSUE TITLE
Changing an item in a vector at a specific index

### ISSUE THREAD

**Issue by Pascal-Ortiz** [tylov/STC#39]
Suppose we have a STC vector:

```C
cvec_z v= cvec_z_init();
cvec_z_push_back(&v, 42);
```
    
What is the STC equivalent function of the assignment operator? I mean, I'm looking for a shortcut to the following code

`v.data[0]=2023`

In C++, we can do either `v.assign(0)=2023 `or `v.at(0)=2023` or `v[0]=2023`.

With STC, we have a getter as the `stc_z_at` function. Similarly, is there a setter function? BTW, it seems that `stc_z_at(&v, 0)=2023 `does not work.

**Comment by tylov** [comment]
v.data[i] = 2023 is as short as it gets and is OK because _data_ is a "public" member.  You can use _at_mut()_ if you want to will check bounds with assert (like at() in c++): 
```
*cvec_z_at_mut(&v, i) = 2023;   
```
If you have e.g. a vector of cstr, you should do one of:
```
cstr_assign(cvec_z_at_mut(&v, i), "Hello");
cstr_assign(&v.data[i], "Hello");
```
