### ISSUE TITLE
ask for `cstr_append_fmt`, `cstr_replace_all`, `cstr_split`

### ISSUE THREAD

**Issue by liigo** [tylov/STC#4]

**Comment by tylov** [comment]
Good suggestions.
Added cstr_assign_fmt(&s, "%s%d", s.str, 100); which works as append_fmt() would.
Added csview_first_token(), csview_next_token() in csview.h, which does split see example.
Added cstr_replace_all()

**Comment by liigo** [comment]
Thank you! Nice work! ❤
