### ISSUE TITLE
Unexpected cmap behavior

### ISSUE THREAD

**Issue by MrPointer** [tylov/STC#42]
## Overview
Hi, this is probably more of a discussion/question rather than a definite issue, but since discussions are disabled for this project, I have no other option.  
Anyway, I encountered strange behavior with cmap, either because I misunderstand the API or because of a real issue.  

### Use-Case
I have a scenario where I need to have a `map<user-key, cvec>` where the `user-key` is just a POCO struct, without pointers. The `cvec` is a `vector<uint8_t>`, i.e. vector of bytes. The keys are compared using `c_memcmp_eq`  
When a new block has to be inserted, it depends on whether the key already exists:
* If it exists - The vector is appended to
* It it doesn't - A new map entry is created, with the given key and a new vector to contain the given block  

To do this I'm using `cmap_X_find`, and checking its return value to know whether the key exists. **I'm assuming** that `iter.ref == NULL` is the correct check in this case!
Also, map entries may be erased as a response to some events, and I've defined `#define i_valdrop cvec_X_drop` to ensure it properly drops the vector value.  

In one particular flow (which I can always easily reproduce), a new map entry is created, consumed, and then immediately erased. Following that is another entry, with a different key and block, **however**, `cmap_X_find` returns an iterator whose `ref` field isn't equal to `NULL`, rather, its' `first` (`iter.ref->first`) is the same as the first key _**which has been erased**_!  

### Code Sample
For convenience, here's a quick sample (names have been obfuscated) of my scenario in code:  
```c
#include <stddef.h>
#include <stdint.h>

typedef struct data_block_id
{
    uint16_t msg_id;
    uint16_t source_id;
} data_block_id_t;

typedef enum
{
    PUT_SEGMENT_OK = 0,
    PUT_SEGMENT_MEMORY_ALLOCATION_FAILED,
    PUT_SEGMENT_FAILED,
    RELEASE_BLOCK_OK,
    RELEASE_BLOCK_FAILED
} err_e;

#define i_val uint8_t
#define i_tag block
#include <stc/cvec.h>

#define i_key data_block_id_t
#define i_val cvec_block
#define i_eq c_memcmp_eq
#define i_valdrop cvec_block_drop
#define i_valclone cvec_block_clone
#define i_tag message
#include <stc/cmap.h>

err_e put_block(void *const block_container, data_block_id_t const *const block_id, uint8_t const *const data,
                size_t data_size)
{
    cmap_message *map = (cmap_message *)block_container;

    cmap_message_iter found_block_item = cmap_message_find(map, *block_id);
    if (found_block_item.ref == NULL)
    {
        // Key doesn't exist yet, it's a new message buffer
        cvec_block message_block = cvec_block_with_capacity(data_size);
        cmap_message_result insert_result = cmap_message_insert(map, *block_id, message_block);
        if (!insert_result.inserted)
        {
            if (insert_result.nomem_error)
                return PUT_SEGMENT_MEMORY_ALLOCATION_FAILED;
            return PUT_SEGMENT_FAILED;
        }
        found_block_item.ref = insert_result.ref;
    }

    for (size_t i = 0; i < data_size; i++)
    {
        cvec_block_push_back(&found_block_item.ref->second, *(data + i));
    }

    return PUT_SEGMENT_OK;
}

err_e release_block(void *const block_container, data_block_id_t const *const block_id)
{
    cmap_message *msg_parts_map = (cmap_message *)block_container;
    size_t erase_rc = cmap_message_erase(msg_parts_map, *block_id);
    return erase_rc == 1 ? RELEASE_BLOCK_OK : RELEASE_BLOCK_FAILED;
}

int main()
{
    cmap_message msg_map = cmap_message_init();
    uint8_t sample_data[] = { 1, 2, 3 };
    data_block_id_t first_block = { .msg_id = 1, .source_id = 0 };
    data_block_id_t second_block = { .msg_id = 1, .source_id = 1 };

    put_block(&msg_map, &first_block, sample_data, sizeof(sample_data));
    release_block(&msg_map, &first_block);

    put_block(&msg_map, &second_block, sample_data, sizeof(sample_data));

    cmap_message_drop(&msg_map);
}
```

## Environment
OS: x86-64 Linux (Ubuntu 20.04)
stc version: 3.9
Installed via: [Conan](https://conan.io/center/stc), using latest ref (3.9)

Any help is much appreciated! Thanks 🙂

**Comment by tylov** [comment]
Hi, I have looked at your code, and I don't find any problems. I added a loop to insert and erase sequentially, but see no problems. The default hash function should work fine with that key, as well as memcmp for equality. Are you sure this is the state of the code when you got the error, e.g. could some other part of your code overwrite memory of the cmap?
PS. I will enable discussions for the project. 

A few notes on your code:
- You can use `#define i_valclass cvec_block` instead of `i_val` when the value type is a "class", i.e. has _drop(), _clone() functions. Then you don't need to specify them. Works for all STC containers as elements in containers. (also for keys, but the most useful `cstr` uses uses it's own "meta" macro `i_key_str` which adds "automatic" conversion to/from char*).
- I just removed the `nomem_error` from the result type. Test for result.ref == NULL instead. If result.inserted is true, result.ref is not NULL.
- You don't have to do the pre-lookup unless it is important to insert a pre-reserved/made vector into the map:
```
// cvec_init() returns just a 24-bytes NULL struct.
cmap_message_result insert_result = cmap_message_insert(map, *block_id, cvec_block_init());
if (insert_result.ref == NULL)
    return MEM_FAIL;
if (insert_result.inserted) 
    for (...) 
        cvec_block_push(&insert_result.ref->second, *(data + i));
else
    /* insert_result.ref->second is an already inserted vector. */
```

**Comment by MrPointer** [comment]
@tylov Thanks for the quick response and mini-CR, you've pointed out good things indeed!  
As for the root cause - Try to run/debug the sample code in the description, it's happening there as well, it really can't get any simpler 😅

**Comment by MrPointer** [comment]
@tylov Just tried the `#define i_valclass cvec_block` tip, but it fails to compile!  
For some reason, it treats the value as `struct data_block_id *` (??) - Do you think it might have something to do with the fact I'm using this library via Conan, which seems like a non-official source?

**Comment by tylov** [comment]
I see, you are using a bit older version, there has been some API changes in 4. for sure.
I saw you last comment, but I think there is a bug in the older version 3 (not sure when I fixed it):

I am now pretty sure what the error you are getting is: In the version you are using, there was a bug in the find() function when used on an empty map, which is exactly what you are doing. The current version tests map size > 0.

**Comment by MrPointer** [comment]
@tylov Do you happen to maintain the Conan recipe for this library as well? Or is it someone else? Guessing from the author in Conan's GitHub repo, it's someone else, but you can never be sure 😁  
If you're not, and indeed it's someone else, do you communicate with each other? Because stc versions aren't released to Conan that often, there's a bump from `3.5` straight to `3.9`

**Comment by tylov** [comment]
No, I haven't maintained the Conan recipe. But I have been bad with releases, so it's partly my fault that there is a big jump.
I will release a version 4.1 rather soon, and hopefully make more steady releases after that. That said, I want the library to go into a maintenance phase, as I am quite pleased with its current state. Mainly improving docs, do cleanup and freeze the API as much as possible.

**Comment by MrPointer** [comment]
Thanks for the feedback. Once it's released I'll try to contact the recipe maintainer myself to urge them to support the new version, or do it myself if it's possible.  
Could you at least make an official release on Github? That's the only way I could get notified about it 🙂 

Anyway, it's off-topic, the original issue has been resolved so I'm closing this, thanks a lot again! 🙏🏻
