### ISSUE TITLE
Can't compile clist with the -Wunused-parameter compiler flag

### ISSUE THREAD

**Issue by Monochrome-Sauce** [tylov/STC#45]
When using the `clist` container, the code must be compiled with `-Wno-unused-parameter` because of lines 137 and 164 in `stc/clist.h`.

The code in line 137 is:
```
STC_INLINE bool
_cx_memb(_reserve)(_cx_self* self, size_t n)
{
    return true;
}
```
The solution is to simply add `(void)self;` and `(void)n;` inside of the function definition.

I know I could've made a pull/merge-request, but I believe such a small thing is faster to report through an issue.

**Comment by tylov** [comment]
Thanks, I'll add it. This function is there only for possible generic algorithms (i.e macro) where you can fill a container with data by first calling reserve(), which all other containers support (along with push() and some others).

Version 4.1 is soon ready where I will make an real release of. (just merged a dev branch to master).

**Comment by tylov** [comment]
Pushed in last commit.
