### ISSUE TITLE
How to define 2D vectors?

### ISSUE THREAD

**Issue by AlienKevin** [tylov/STC#49]
I'm trying to define a 2D float vector and encountered several questions. My current approach is to:
```c
#define i_type FVec
#define i_val float
#include "stc/cvec.h"

#define i_no_cmp
#define i_type FVec2D
#define i_val FVec
#include "stc/cvec.h"
```
Questions:
1. I want to check for equality between two `FVec2D` but am not interested in LT or GT relationships. How do I define `i_eq` for `FVec2D`?
2. Do I need to implement a custom `drop` for `FVec2D` or the default implementation automatically calls `FVec`'s drop?
3. Similarly, do I need to implement `clone` for `FVec2D`?

I just discovered your library today from a reddit answer and I think it's really cool. I'm relatively new to C and the lack of standard containers really tripped me up. Coming from a Rust and Python background, many of the terms/functions look familiar. It's impressive that you managed to pull of some type-safe psuedo-polymorphism just using macros.

**Comment by tylov** [comment]
I may add these in the future as it is quite easy. But you can do it for your vectors:
You could use cspan for 2D arrays if they have gotten a fixed size. PS, this is not checked for syntax errors.
```c
bool FVec_eq(FVec* v1, FVec* v2);
#define i_type FVec
#define i_eq FVec_eq
#define i_val float
#include "stc/cvec.h"

bool FVec2_eq(FVec2* v1, FVec2* v2);
#define i_type FVec2
#define i_eq FVec2_eq
#define i_val FVec
#include "stc/cvec.h"

#include "stc/cspan.h"
using_cspan2(FSpan, float); // defines FSpan and FSpan2

bool FVec_eq(FVec* v1, FVec* v2) {
    for (FVec_iter i1 = FVec_begin(v1), i2 = FVec_begin(v2); i1.ref && i2.ref; FVec_next(&i1), FVec_next(&i2)) {
        if (*i1.ref != *i2.ref) return false;
    return i1.ref == NULL && i2.ref == NULL;
}

bool FVec2_eq(FVec2* v1, FVec2* v2)
    for (FVec2_iter i1 = FVec2_begin(v1), i2 = FVec2_begin(v2); i1.ref && i2.ref; FVec2_next(&i1), FVec2_next(&i2)) {
        if (!FVec_eq(i1.ref, i2.ref)) return false;
    return i1.ref == NULL && i2.ref == NULL;
}

int main()
{
    FVec v = c_make(FVec, {1, 2, 3.1415, 4, 5, 6, 7, 8, 9});
    FVec2 v2 = c_make(FVec2, {v});
    
    // You can also make 2D spans from FVec when the vector is built.
    FSpan2 fs2 = cspan_md(v.data, 3, 3);
    FSpan fs = cspan_submd(&fs2, 1);    // fs2[1], etc.
}
```

**Comment by AlienKevin** [comment]
Got it, thanks for detailed explanation. I will give it a try later.
