### ISSUE TITLE
Directory structure so that not all files are in include paths

### ISSUE THREAD

**Issue by Kamilcuk** [tylov/STC#5]
The current build scripts add the root directory of the project to include paths, ex in [here](https://github.com/tylov/STC/blob/master/benchmarks/run_gcc.sh#L1):

    g++ -I.. -O3 -o cdeq_benchmark.exe   cdeq_benchmark.cpp

This adds __all files__ in the repository to include paths, __all files__, which for example causes erroneous code to compile, ex:

    #include <docs/carray_api.md>   // it is in include path...

Please consider moving `stc` directory inside some ex. `src` or `include` directory.

This affects projects that would want to use this repo via just cloning and adding to include path.

**Comment by tylov** [comment]
Thanks, it is on my TODO.  I Will soon make a Release V2.0 RC, where it will be included and the API should be stable.

**Comment by Kamilcuk** [comment]
I did here some commits: https://github.com/Kamilcuk/STC/commits/master just for fun, may it serve as an example

**Comment by tylov** [comment]
Great. The library needs a proper build setup and a test suite. It is still quite small and simple to deploy, but it has lots of functionality that is not covered by benchmarks and examples.

**Comment by tylov** [comment]
Moved .h files to include/stc folder.
