### ISSUE TITLE
getting errors when using c_forvar macro from STC 1.2

### ISSUE THREAD

**Issue by notevenodd** [tylov/STC#9]
GCC isn't happy with the "c_forvar" macro from latest STC. It gives this error:

```c
include/stc/ccommon.h:126:47:
error: _c_ii undeclared (first use in this function)                                                 
 #define c_forvar(acquire, ...) for (acquire, *_c_ii = NULL; !_c_ii; ++_c_ii, __VA_ARGS__)
...
```

---

I had a quick look at the `ccommon.h` file and saw _c_ii isn't declared in c_forvar:
```c
#define c_forvar(acquire, ...) for (acquire, *_c_ii = NULL; !_c_ii; ++_c_ii, __VA_ARGS__)
```
By the way, is this "guardian" variable `_c_ii` supposed to be some pointer ? Just below it, `c_defer` is defined like this:
```c
#define c_fordefer(...) for (int _c_ii = 0; !_c_ii; ++_c_ii, __VA_ARGS__)
```
I guess the compiler would eliminate those only-one-iteration loops in -O2 mode. But in any case, if I write a `for` that loops a small amount of times, I declare the counter variable as `uint_fast8_t`.

**Comment by tylov** [comment]
The documentation specifies that the usage must be of the form:
`c_forvar (SomeType var = someInit, destructions, ...)`. You can skip the `= someInit` part as well, but you need to declare a variable. If you already have declared (and initialized) it outside, you should use c_fordefer() which only does the destruction/release part.

**Comment by notevenodd** [comment]
My apologies!
I had my variable already defined and was using c_forvar to assign it instead of declaring it.
I close the issue!!!

**Comment by tylov** [comment]
no problem.

**Comment by notevenodd** [comment]
Actually, now I wrote my own, because sometimes I want an init╱end scope that is not based on declaring a variable
```c
#define c_forinitend(begin, ...) for (int _c_ii = (init, 0); !_c_ii;  ++_c_ii, __VA_ARGS__)
```

👍

**Comment by tylov** [comment]
Yes, but many c_for... macros now.  I may redefine c_fordefer() to this. In that case one must remember to use it like: `c_fordefer (0, release, ...)`. when there is no init.

**Comment by tylov** [comment]
I added c_forscope() macro, identical to c_forinitend().
